In [2]:
import numpy as np 

## Question 3: Matrix determinants

In [10]:
M = np.array([
    [1, 0, 1], 
    [0, 1, 0], 
    [1, 1, 1]
])

N = np.array([
    [2, 8, 7], 
    [4, 3, 9], 
    [1, 9, 5]
])

M_det = np.linalg.det(M)

N_det = np.linalg.det(N)

result = M_det * N_det

print(result)


0.0


### Find the cov matrix

In [34]:
# Data 
data = np.array([
    [3, 2], 
    [5, 8]
])

# Get means 
mean_0 = np.mean(data[:,0])
mean_1 = np.mean(data[:, 1])

# Create matrix of means mu 
mu = np.array([mean_0, mean_1])

### Alternatively, we can directly get it by 
mu = np.mean(data, axis=0)

print(mu)

[4. 5.]


In [36]:
# We can use broadcasting to center the data
centered_data = data - mu 

print(centered_data)

[[-1. -3.]
 [ 1.  3.]]


In [ ]:
# Create the transpose 
print(centered_data.T)

[[-1.  1.]
 [-3.  3.]]


In [ ]:
(1/(len(data) - 1)) * centered_data.T @ centered_data

array([[ 2.,  6.],
       [ 6., 18.]])

2